import { EconomicIndicator } from './types';

export const ECONOMIC_INDICATORS: EconomicIndicator[] = [
  {
    id: 'nonfarm-payrolls',
    name: '非农就业人口',
    nameEn: 'Nonfarm Payrolls',
    description: '衡量美国非农业部门新增就业人数，是美联储货币政策的核心参考指标之一',
    schedule: '每月第一个周五（美东时间上午8:30）',
    importance: 5,
    category: 'employment',
    fredSeriesId: 'PAYEMS',
    unit: '千人',
    marketImpact: {
      beat: '美元走强，美债收益率上升，股市反应不一',
      miss: '美元走弱，美债收益率下降，避险情绪上升',
      inline: '市场波动有限，维持现有趋势',
    },
  },
  {
    id: 'unemployment-rate',
    name: '失业率',
    nameEn: 'Unemployment Rate',
    description: '劳动力市场健康程度的关键指标，美联储双重使命之一',
    schedule: '每月第一个周五（与非农同步发布）',
    importance: 5,
    category: 'employment',
    fredSeriesId: 'UNRATE',
    unit: '%',
    marketImpact: {
      beat: '失业率低于预期，显示经济强劲，美元可能走强',
      miss: '失业率高于预期，经济走弱信号，市场可能定价降息',
      inline: '符合预期，市场关注非农数据',
    },
  },
  {
    id: 'cpi',
    name: '消费者物价指数（CPI）',
    nameEn: 'Consumer Price Index',
    description: '衡量通货膨胀的主要指标，直接影响美联储利率决策',
    schedule: '每月中旬（数据发布日前一个月的数据）',
    importance: 5,
    category: 'inflation',
    fredSeriesId: 'CPIAUCSL',
    unit: '同比%',
    marketImpact: {
      beat: 'CPI超预期，通胀压力大，美联储可能维持高利率甚至加息',
      miss: 'CPI低于预期，通胀降温，市场可能定价降息',
      inline: '符合预期，维持现有货币政策预期',
    },
  },
  {
    id: 'core-cpi',
    name: '核心CPI',
    nameEn: 'Core CPI (ex Food & Energy)',
    description: '剔除食品和能源的核心通胀指标，更能反映长期通胀趋势',
    schedule: '与CPI同步发布',
    importance: 5,
    category: 'inflation',
    fredSeriesId: 'CPILFESL',
    unit: '同比%',
    marketImpact: {
      beat: '核心通胀高企，美联储政策偏鹰，利率长期维持高位',
      miss: '核心通胀下行，降息预期升温，债市走强',
      inline: '符合预期，市场关注美联储表态',
    },
  },
  {
    id: 'pce',
    name: '个人消费支出物价指数（PCE）',
    nameEn: 'PCE Price Index',
    description: '美联储首选通胀指标，2%为政策目标',
    schedule: '每月最后一个工作日前后',
    importance: 5,
    category: 'inflation',
    fredSeriesId: 'PCEPI',
    unit: '同比%',
    marketImpact: {
      beat: 'PCE超预期，降息时间表推迟，美元走强',
      miss: 'PCE低于预期，降息预期提前，债市和黄金受益',
      inline: '基本符合预期，关注美联储声明',
    },
  },
  {
    id: 'gdp',
    name: '国内生产总值（GDP）',
    nameEn: 'GDP Growth Rate',
    description: '衡量美国经济整体规模和增长速度的核心指标',
    schedule: '季度发布（初值、修正值、终值）',
    importance: 4,
    category: 'gdp',
    fredSeriesId: 'GDP',
    unit: '十亿美元',
    marketImpact: {
      beat: 'GDP超预期，经济强劲，支撑美元和股市',
      miss: 'GDP低于预期，衰退担忧上升，避险资产受益',
      inline: '符合预期，市场聚焦通胀和就业数据',
    },
  },
  {
    id: 'ism-manufacturing',
    name: 'ISM制造业PMI',
    nameEn: 'ISM Manufacturing PMI',
    description: '衡量制造业活动的领先指标，50以上代表扩张',
    schedule: '每月第一个工作日',
    importance: 3,
    category: 'pmi_retail',
    fredSeriesId: 'MANEMP',
    unit: '指数',
    marketImpact: {
      beat: '制造业扩张，经济前景乐观，风险资产走强',
      miss: '制造业收缩，经济放缓信号，避险情绪上升',
      inline: '符合预期，等待服务业PMI数据',
    },
  },
  {
    id: 'retail-sales',
    name: '零售销售',
    nameEn: 'Retail Sales',
    description: '衡量消费者支出的重要指标，消费占美国GDP约70%',
    schedule: '每月中旬（前月数据）',
    importance: 4,
    category: 'pmi_retail',
    fredSeriesId: 'RSXFS',
    unit: '百万美元',
    marketImpact: {
      beat: '消费者支出强劲，经济韧性显现，降息预期下降',
      miss: '消费者支出疲软，经济放缓担忧，市场押注降息',
      inline: '符合预期，维持现有经济评估',
    },
  },
  {
    id: 'housing-starts',
    name: '新屋开工',
    nameEn: 'Housing Starts',
    description: '衡量房地产市场活动的重要指标，对GDP有乘数效应',
    schedule: '每月第三周',
    importance: 3,
    category: 'housing',
    fredSeriesId: 'HOUST',
    unit: '千套',
    marketImpact: {
      beat: '房地产市场活跃，经济信心提升，建材和银行股受益',
      miss: '房地产市场降温，反映高利率影响，可能加速降息预期',
      inline: '房地产市场平稳，等待其他经济数据',
    },
  },
  {
    id: 'existing-home-sales',
    name: '成屋销售',
    nameEn: 'Existing Home Sales',
    description: '反映房地产市场需求，受抵押贷款利率影响显著',
    schedule: '每月第三或第四周',
    importance: 3,
    category: 'housing',
    fredSeriesId: 'EXHOSLUSM495S',
    unit: '百万套（年化）',
    marketImpact: {
      beat: '房屋需求强劲，消费者信心好转，房地产相关股受益',
      miss: '高利率压制购房需求，房地产市场承压',
      inline: '市场消化数据，关注库存和价格变化',
    },
  },
];
